### ISSUE TITLE
Is that possible to display flash mode for the Video Capture

### ISSUE THREAD

**Issue by jamariya** [afollestad/material-camera#136]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Camera.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.4.2`
 - Device OS version: `6.0.1`
 - Device Name: `Nexus 5`

Hello,

Is that possible to display the flash mode on Video recording? Flash is working correctly for the singleShot but flash icon not display while recording the video?

Thanks in advance.

**Comment by tylerkrupicka** [comment]
Hey @jamariya! Unfortunately, the flash during video (Torch Mode) is not currently implemented in material-camera. @sugarmanz and I implemented a lot of the logic for flash in stillshot, and have plans to try to add flash to video as well as soon as we have some free time.  I'm going to close this issue for the time being, because https://github.com/afollestad/material-camera/issues/51 is another older ticket related to adding flash support to video. We'll keep discussion for this feature over on that ticket in the future; feel free to comment if you have any other questions.
