### ISSUE TITLE
Preview is stretched on some devices

### ISSUE THREAD

**Issue by tuandt-gem** [afollestad/material-camera#46]
I run on Sony Xperia M4 Aqua Dual E2312 and preivew screen looks like stretched.

Could you fix it?
![screenshot_2016-04-25-10-55-19 1](https://cloud.githubusercontent.com/assets/15668032/14773547/7069d5b0-0ad5-11e6-9bc8-124add84df9c.png)

**Comment by ManicMapple** [comment]
Unfortunately this also seems to effect the resulting video. I have set
.videoPreferredHeight(720)
.videoPreferredAspect(16f / 9f)

and it results in a stretched video on at least
motorolla g2
samsung galaxy s4
samsung galaxy s7

Until recently I used the commit https://github.com/afollestad/material-camera/commit/8f51691d2e5fdba1efb54befd9ed12e3649926e4 where this problem did not occur and checked every commit after that for changes that might affect this -  but the only thing I can think of is an update in one of the libs (material dialogs maybe?)

**Comment by afollestad** [comment]
@ManicMapple my Material Dialogs library couldn't have any affect on video previews.

**Comment by ManicMapple** [comment]
@afollestad I guess the problem is the surface. http://stackoverflow.com/questions/22105251/android-mediarecorder-aspect-ratio-incorrect

The cases where I had Problems were when preview size (chooseOptimalSize()) and videosize (chooseVideoSize()) had different aspects. (1280x720 vs 960x720)

I solved teh problem (for me, badly) by using the video size as preview size...  This way the videos had the correct aspect.

Sadly, on samsung galaxy s7 thsi dows not help... the video is just a still image.

**Comment by afaucogney** [comment]
Same issue on my Galaxy S4 Advanced

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.6
